helm_hpa_c3eec42e2a68545c94bf589984724381:
    enabled: true
    max_replicas: 2
    min_replicas: 1
    name: ""
    target_cpu_utilization_percentage: 50
    target_memory_utilization_percentage: 50
    workload_kind: Deployment
    workload_name: ""
helm_ingress_b8ccb1ce12845cbf8bfc3c844fb776c3:
    annotations:
        kubernetes.io/ingress.allow-http: "false"
    class_name: ""
    default_backend_name: ""
    default_backend_port: 80
    labels:
        service: myapp
    name: ""
    rules: []
    tls: ""
helm_service_account_c220651b88d857ff9188a1a66b8dd165:
    annotations: {}
    automount: false
    labels: {}
    name: ""
helm_service_fc2b757e88c7553c9e7f950982296f55:
    name: ""
    port: 80
    protocol: TCP
    selector_labels:
        service: myapp
    target_port: 80
    type: ClusterIP
helm_workload_a0fe97fd4d0155e781d867d1dff417c1:
    env: {}
    env_from_config: []
    env_from_secret: []
    image: ""
    image_pull_policy: Always
    image_pull_secret: null
    image_tag: ""
    kind: Deployment
    labels:
        service: myapp
    name: ""
    port: 80
    protocol: TCP
    replicas: 1
    service_account: ""
    volume_mounts: []
    volumes: []
