apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_c220651b88d857ff9188a1a66b8dd165.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_c220651b88d857ff9188a1a66b8dd165.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_c220651b88d857ff9188a1a66b8dd165.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_c220651b88d857ff9188a1a66b8dd165.automount }}
