{{- if .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.workload_kind }}
    name: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.workload_name }}
  minReplicas: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.min_replicas }}
  maxReplicas: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.max_replicas }}
  metrics:
    {{- if .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.target_cpu_utilization_percentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.target_cpu_utilization_percentage }}
    {{- end }}
    {{- if .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.target_memory_utilization_percentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.helm_hpa_c3eec42e2a68545c94bf589984724381.target_memory_utilization_percentage }}
    {{- end }}
{{- end }}